[package]
name = "rpi-hwctl"
version = "0.1.0"
authors = ["Volker Kempert <volker.kempert@almedso.de>"]
edition = "2018"

[dependencies]
si7021 = "0.2.0"
i2cdev = "0.4.1"
i2csensors = "0.1.3"
ssd1306 = "0.3.1"
display-interface-spi = "0.4"
linux-embedded-hal = "0.3.0"
embedded-graphics = "0.6.2"

